[version]
source = "vcs"

[build.hooks.vcs]
version-file = "wizard_template/_version.py"

[envs.default]
description = "Base development environment"
dependencies = ["coverage[toml]", "pre-commit", "pytest-cov", "pytest"]

[envs.default.scripts]
_wizard = ["python ./scripts/rename_project_content.py"]
pre-commit-install = "pre-commit install {args}"
pre-commit-uninstall = "pre-commit uninstall {args}"
check = "pre-commit run {args} --all-files"
type = "check mypy {args}"
lint = "check ruff {args}"
format = "check ruff-format {args}"
test = "pytest --cov --cov-report=term {args}"
test-no-cov = "test --no-cov {args}"
qa = ["check", "test", "echo '✅ QA passed'"]

[envs.test]
description = "Extended test environment"
extra-dependencies = ["pytest-randomly", "pytest-rerunfailures", "pytest-xdist"]

[envs.test.scripts]
extended = "test -n auto --reruns 7 --reruns-delay 1 {args}"

[[envs.test.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[envs.docs]
description = "Documentation environment"
dependencies = ["docutils", "jupyter-book", "sphinx-autobuild"]
detached = true
skip-install = false

[envs.docs.scripts]
config = "jupyter-book config sphinx docs {args}"
build = ["config", "jupyter-book build docs --path-output build {args}"]
serve = [
    "config",
    "sphinx-autobuild docs build/_build/html --open-browser --watch wizard_template {args}",
]

[envs.changelog]
description = "Changelog handler"
dependencies = ["towncrier"]
detached = true

[envs.changelog.scripts]
build = "towncrier build {args}"
draft = "build --draft {args}"
create = "towncrier create {args}"
check = "towncrier check {args}"
