name: Docs

# See:
# https://jupyterbook.org/en/stable/publish/gh-pages.html
on:
  release:
    types: [published] # trigger when new versions is published
  workflow_dispatch: # allow manual triggering

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Hatch
        run: python -m pip install hatch

      - name: Build the book
        run: hatch run docs:build

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.9.3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/_build/html
